### ISSUE TITLE
My sequence contains N

### ISSUE THREAD

**Issue by PEHGP** [chedinlab/rlooper#2]
Hi,
My sequence contains N.
This tool does not seem to be able to handle sequences containing N.
```
terminate called after throwing an instance of 'InvalidSequenceDataException'
  what():  The following character in the input sequence is unrecognized: N
```

Best,
kuan

**Comment by garden-of-delete** [comment]
Hi Kuan, 

You are correct, and this is by design. R-looper does not accept 'N' in the input sequence because the sequence needs to be fully specified to compute the base-pairing energetics accurately. 

Best, 
-- Robert

**Comment by PEHGP** [comment]
Hi Robert
Thank you very much.
I have another question.
Can this tools be used for genome-wide rloop prediction ?
Best,
--kuan

**Comment by garden-of-delete** [comment]
Because our model is built on both base-pairing energetics, and information about topology, doing genome-wide prediction in a way that leverages the model's strengths would require intimate knowledge of the distribution of topology in the genome. Unfortunately detailed maps of topology in the genomes of living cells are not available at that time. Also, the computing probabilities genome-wide would require significant computational resources as well.

Best, 
-- Robert
