### ISSUE TITLE
How to interpret output files

### ISSUE THREAD

**Issue by mmferrari** [chedinlab/rlooper#4]
Hi,
I am a mathematician and I am using rlooper to analyze some DNA sequences.
The command I run is `rlooper test_sequence.fa test_output --N auto` and I get the following output files: `test_output_avgG.wig`, `test_output_bpprob.bed`, `test_output_bpprob.wig`, `test_output_mfe.bed` and `test_output_mfe.wig`.
Can you explain me which output file is what?
I have also seen that you mentioned a manual in issue chedinlab/rlooper#1, can you provide a link?

If you need any other info, please let me know.

Thanks.

**Comment by garden-of-delete** [comment]
Sure. 
- test_output_bpprob.wig is a .wig track viewable in the genome browser (if using genomic sequence) that gives the probability of each base pair being found in an R-loop state. 
- test_output_avgG.wig gives instead the local energy landscape at each base in the sequence, in kcal/mol. More negative values indicate more favorability for R-loop formation. 
- test_output_bpprob.bed is a bedfile of peaks called on the bpprob signal. Likewise, test_output_mfe.bed should contain a single peak for each gene at the at the lowest energy structure. Note, both of these files will only be populated if the `--bedfile` and `--sensitivity` options are specified. Seen the manual for more details. 

As for Issue #1, that was being caused by an improperly formatted fasta header at the top of the input sequence. The manual provides a clear example of what a properly formatted fasta header should look like. If you want to attach or send me your input file, I can double check the header for you. 

Best,
-- Robert

**Comment by mmferrari** [comment]
This is the header `>test_sequence range=HIS3:1-892 5'pad=0 3'pad=0 strand=-`.

Regarding the file output description, you didn't mention the `test_output_mfe.wig`. Does it have the same content as `test_output_mfe.bed`?

Thanks for your help.

**Comment by garden-of-delete** [comment]
essentially yes, the .wig and the .bed are just different forms of the same thing with respect to the minimum free energy structure. 

If you are still having issues with the header, try the following:
 `>test_sequence range=HIS3:1-892 5'pad=0 3'pad=0 strand=- repeatMasking=none`

**Comment by mmferrari** [comment]
Hi,
I used the header you suggested  `>test_sequence range=HIS3:1-892 5'pad=0 3'pad=0 strand=- repeatMasking=none` with the following command 
`rlooper test_sequence.fa test_output --N auto --bedfile`.
None of the files `test_output_bpprob.bed` and `test_output_mfe.bed` have been populated. I also tried to lower the `--sensitivity` parameter but the output did not change.

What else can I try?

Thanks.

**Comment by garden-of-delete** [comment]
That seems correct to me. The default sensitivity should be good for calling at least the minimum free energy peak. Have you tried visualizing the _bpprob.wig file to see what it looks like?

Also, if you provide me with the .fa file you are testing with I can try to replicate the problem.

**Comment by mmferrari** [comment]
The _bpprob.wig as well as the _mfe.wig file have been populated. I did not visualize these files in the genome browser because my sequences are artificial. I plan to do it as soon as my collaborators send me the whole chromosome sequence.
I am sending the .fa (here the sequence is 663bp long, instead of 892bp, but the problem is still there).
[test_sequence.fa.txt](https://github.com/chedinlab/rlooper/files/3239269/test_sequence.fa.txt)

**Comment by garden-of-delete** [comment]
I added a simple visualization script in python to the repository and usage information to the readme. I will take a look at your sequence tomorrow to make sure there are no issues.
